# Jekyll configuration for GitHub Pages
# Exclude test directories and Python files from Jekyll processing

exclude:
  - manual_tests/
  - tests/
  - coffee_maker/
  - scripts/
  - .pytest_cache/
  - .mypy_cache/
  - .ruff_cache/
  - __pycache__/
  - "*.py"
  - "*.pyc"
  - .venv/
  - venv/
  - .env
  - .git/
  - .github/
  - .gitignore
  - poetry.lock
  - pyproject.toml
  - pytest.ini
  - .pre-commit-config.yaml
  - Makefile
  - requirements*.txt
  # Exclude docs with Liquid-like syntax that breaks Jekyll
  - docs/architecture/SPEC_IMPROVEMENT_REVIEW_2025-10-17.md
  - docs/architecture/TEAM_ACCELERATION_OPPORTUNITIES.md
  - docs/roadmap/PRIORITY_5_5_STRATEGIC_SPEC.md

# GitHub Pages settings
theme: jekyll-theme-primer
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
