# Custom pre-commit hooks for My Project
repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--line-length=120]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1 # Use a recent version of autoflake
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables # Uncomment if you also want to remove unused variables
          - --expand-star-imports # Uncomment if you want to expand star imports (e.g., from ... import *)
          # - --ignore-init-module-imports # Optional: if you have __init__.py files where imports are intentionally "unused" but needed for the package interface
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
