# .github/workflows/reusable-ci-checks.yml
# co-author : Gemini 2.5 Pro Preview

name: Reusable CI Checks

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: true
        type: string
      os:
        description: 'Operating system to run on'
        required: false
        type: string
        default: 'ubuntu-latest'
      # This input now controls the environment variable directly
      COFFEE_MAKER_RUN_CI_TESTS_VALUE:
        description: 'Value for COFFEE_MAKER_RUN_CI_TESTS env var (e.g., "True" or "False")'
        required: false
        type: string
        default: "True" # Default behavior if caller doesn't specify
    # 'secrets:' block for workflow inputs is removed as we are not passing repo secrets for this flag

jobs:
  perform-checks:
    name: CI Checks on Python ${{ inputs.python-version }} OS ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry virtualenv
        uses: actions/cache@v4
        id: poetry-cache
        with:
          path: .venv
          key: ${{ inputs.os }}-poetry-${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ inputs.os }}-poetry-${{ inputs.python-version }}-

      - name: Install dependencies (if cache miss)
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --with dev --no-root

      - name: Install project and all dependencies
        run: poetry install --no-interaction --with dev

      - name: Run tests (pytest)
        env:
          # Use the input value directly for the environment variable
          COFFEE_MAKER_RUN_CI_TESTS: ${{ inputs.COFFEE_MAKER_RUN_CI_TESTS_VALUE }}
        run: |
          echo "pytest will run with COFFEE_MAKER_RUN_CI_TESTS=${{ inputs.COFFEE_MAKER_RUN_CI_TESTS_VALUE }}"
          poetry run pytest tests/ci_tests/ -v

      - name: Run pip-audit
        run: |
          poetry run pip-audit
          # This will fail the job if pip-audit finds vulnerabilities and exits non-zero.
