# .github/workflows/run-ci-tests.yml
# co-author : Gemini 2.5 Pro Preview

name: ci-tests-and-reports

on:
  push:
    branches: [ "main" ]
#  pull_request: # Run on pull requests targeting main
#    branches: [ "main" ]
  release:
    types: [published] # Runs when a release is published.
  workflow_dispatch: # Manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Job that calls the reusable CI checks
  ci_checks_job:
    name: Perform CI Checks
    uses: ./.github/workflows/reusable-ci-checks.yml # Path to your reusable workflow
    with:
      python-version: "3.12" # Or use matrix strategy here if needed
      os: 'ubuntu-latest'
    env:
      COFFEE_MAKER_RUN_CI_TESTS: ${{ secrets.COFFEE_MAKER_RUN_CI_TESTS }}

  # Job for deploying reports to Pages - depends on the CI checks job
  deploy_reports_job:
    name: Prepare and Deploy Reports to GitHub Pages
    runs-on: ubuntu-latest
    needs: [ci_checks_job] # Depends on the reusable CI checks passing
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Condition for deployment (only on main push, release, or manual trigger)
    # The artifact generation steps within this job will run if `always()` is true
    # but the final `deploy-pages` action is further conditioned by the event type.
    if: >
      always() &&
      (
        (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
        (github.event.name == 'release' && github.event.action == 'published') ||
        (github.event_name == 'workflow_dispatch')
      )

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12 # Specific version for this job's tools
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies (for report generation tools if any)
        run: poetry install --no-interaction --with dev

      - name: Generate Coverage report for Pages
        env:
          COFFEE_MAKER_RUN_CI_TESTS: ${{ secrets.COFFEE_MAKER_RUN_CI_TESTS }}
        run: |
          poetry run pytest tests/ci_tests/ -v --cov=coffee_maker --cov-report=html:reports/coverage

      - name: Generate pip-audit text report for Pages
        run: |
          mkdir -p reports/pip_audit
          poetry run pip-audit --output reports/pip_audit/pip_audit_report.txt || echo "Pip-audit report generation finished (may have found issues or errored)."

      - name: Create overall reports directory for Pages
        run: mkdir -p gh_pages_artifact

      - name: Copy Coverage report to Pages artifact directory
        run: | # if: always() is inherited from the job's if for this step
          if [ -d "reports/coverage" ]; then
            cp -r reports/coverage gh_pages_artifact/coverage
            echo "Coverage report copied."
          else
            echo "Warning: Coverage report directory (reports/coverage) not found."
            mkdir -p gh_pages_artifact/coverage
            echo "<html><body><h1>Coverage report not generated.</h1></body></html>" > gh_pages_artifact/coverage/index.html
          fi

      - name: Copy pip-audit report and HTML wrapper to Pages artifact directory
        run: | # if: always() is inherited
          mkdir -p gh_pages_artifact/pip_audit
          GENERATED_TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          if [ -f "reports/pip_audit/pip_audit_report.txt" ]; then
            cp reports/pip_audit/pip_audit_report.txt gh_pages_artifact/pip_audit/pip_audit_report.txt
            WRAPPER_TEMPLATE_PATH=".github/workflows/pages_templates/pip_audit_wrapper.html"; DEST_WRAPPER_PATH="gh_pages_artifact/pip_audit/index.html"
            if [ -f "$WRAPPER_TEMPLATE_PATH" ]; then cp "$WRAPPER_TEMPLATE_PATH" "$DEST_WRAPPER_PATH"; sed -i "s|<!-- TIMESTAMP -->|$GENERATED_TIMESTAMP|g" "$DEST_WRAPPER_PATH"; echo "pip-audit HTML wrapper copied & timestamped.";
            else echo "Warning: $WRAPPER_TEMPLATE_PATH not found."; echo "<html><body><h1><a href='pip_audit_report.txt'>pip_audit_report.txt</a></h1><p>Wrapper template missing. Generated: $GENERATED_TIMESTAMP</p></body></html>" > "$DEST_WRAPPER_PATH"; fi
          else echo "Warning: reports/pip_audit/pip_audit_report.txt not found."; echo "<html><body><h1>pip-audit report not generated.</h1><p>$GENERATED_TIMESTAMP</p></body></html>" > gh_pages_artifact/pip_audit/index.html; fi

      - name: Create main index.html for GitHub Pages
        run: | # if: always() is inherited
          TEMPLATE_INDEX_PATH=".github/workflows/pages_templates/index.html"; DEST_INDEX_PATH="gh_pages_artifact/index.html"; GENERATED_TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          if [ -f "$TEMPLATE_INDEX_PATH" ]; then cp "$TEMPLATE_INDEX_PATH" "$DEST_INDEX_PATH"; sed -i "s|<!-- TIMESTAMP -->|$GENERATED_TIMESTAMP|g" "$DEST_INDEX_PATH"; echo "Main landing page copied & timestamped.";
          else echo "Error: $TEMPLATE_INDEX_PATH not found. This is a required file."; exit 1; fi
          echo "Main landing page successfully prepared."

      - name: Add .nojekyll
        run: touch gh_pages_artifact/.nojekyll # if: always() is inherited

      - name: Verify Pages artifact contents
        run: | # if: always() is inherited
          echo "Listing contents of gh_pages_artifact directory before upload:"
          ls -Rla gh_pages_artifact

      - name: Upload HTML reports artifact for GitHub Pages
        # This step will run if the job's `if` condition is met due to always() and event type
        uses: actions/upload-pages-artifact@v3
        with:
          path: gh_pages_artifact

      - name: Deploy reports to GitHub Pages
        id: deployment
        # This step uses the same encompassing 'if' condition from the job level.
        # No need to repeat the full condition here if the job's 'if' already gates it correctly for deployment events.
        # However, if you want to be super explicit or add more conditions JUST for deployment action:
        # if: github.event_name == 'push' && github.ref == 'refs/heads/main' || (github.event_name == 'release' && github.event.action == 'published') || github.event_name == 'workflow_dispatch'
        uses: actions/deploy-pages@v4
