# .github/workflows/run-tests.yml
# co-author : Gemini 2.5 Pro Preview

name: Run Python Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test with Python ${{ matrix.python-version }} on ${{ matrix.os }} with COFFEE_MAKER_RUN_TEST = "${{ secrets.COFFEE_MAKER_RUN_TEST }}"
    runs-on: ${{ matrix.os }}
    environment: ci-tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry virtualenv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-${{ matrix.python-version }}-

      - name: Install dependencies (including dev/test dependencies)
        run: poetry install --no-interaction --with dev # Assuming pytest is in 'dev' group
        # If you have a separate 'test' group: poetry install --no-interaction --with test
        # Or if pytest is a main dependency: poetry install --no-interaction

      - name: Run tests and collect coverage data
        env:
          COFFEE_MAKER_RUN_TEST: ${{ secrets.COFFEE_MAKER_RUN_TEST }}
        run: |
          poetry run pytest -v --cov=coffee_maker --cov-report=xml:coverage.xml --cov-report=html:cov_html
          # your_package_name is the name of the Python package you want to measure coverage for.
          # --cov-report=xml:coverage.xml generates an XML report (e.g., for Codecov/Coveralls)
          # --cov-report=html:cov_html generates an HTML report in the 'cov_html' directory

      - name: Upload coverage report (XML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

      - name: Upload coverage report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: cov_html/ # Upload the entire HTML report directory
